### ISSUE TITLE
Upload files fails sometimes

### ISSUE THREAD

**Issue by erolm-a** [denBot/WAD2-Group-Project#35]
I was trying to upload an OVPN file. Here is what happened:

```
[13/Mar/2019 15:16:14] WARNING [backendAPI.views:327] [FILE-UPLOAD] : USER: vittomiamiao FAILED TO UPLOADED FILE WITH ID: cyberchallenge.ovpn FROM IP: 127.0.0.1
Upload for cyberchallenge.ovpn failed
Traceback (most recent call last):
  File "/home/erolm_a/Documenti/Uni/WAD2/WAD2-Group-Project/NootTech/backendAPI/views.py", line 316, in post
    uploaded_file.save()
  File "/home/erolm_a/Documenti/Uni/WAD2/WAD2-Group-Project/NootTech/backendAPI/models.py", line 163, in save
    self.icon = utils.get_fontawesome(self.file_mime_type, self.file_ext)
  File "/home/erolm_a/Documenti/Uni/WAD2/WAD2-Group-Project/NootTech/backendAPI/utils.py", line 130, in get_fontawesome
    mimetype = mimetype.split('/')
AttributeError: 'NoneType' object has no attribute 'split'
[13/Mar/2019 15:16:27] WARNING [backendAPI.views:327] [FILE-UPLOAD] : USER: vittomiamiao FAILED TO UPLOADED FILE WITH ID: cyberrange.ovpn FROM IP: 127.0.0.1
Upload for cyberrange.ovpn failed
Traceback (most recent call last):
  File "/home/erolm_a/Documenti/Uni/WAD2/WAD2-Group-Project/NootTech/backendAPI/views.py", line 316, in post
    uploaded_file.save()
  File "/home/erolm_a/Documenti/Uni/WAD2/WAD2-Group-Project/NootTech/backendAPI/models.py", line 163, in save
    self.icon = utils.get_fontawesome(self.file_mime_type, self.file_ext)
  File "/home/erolm_a/Documenti/Uni/WAD2/WAD2-Group-Project/NootTech/backendAPI/utils.py", line 130, in get_fontawesome
    mimetype = mimetype.split('/')
AttributeError: 'NoneType' object has no attribute 'split'
```

I suspect the cause lies in the way icons are generated in the backend, in particular I suspect there is no fall-back option for unknown file types.

**Comment by erolm-a** [comment]
Oh là là!

```python
>>> from mimetypes import MimeTypes
>>> mime = MimeTypes()
>>> mime.guess_type('test.ovpn')
(None, None)
```
